blank_issues_enabled: true
contact_links:
  - name: Kevacoin Core Security Policy
    url: https://github.com/kevacoin-team/kevacoin_core/blob/master/SECURITY.md
    about: View security policy
  - name: Kevacoin Team Developers
    url: https://kevacointeam.org
    about: Kevacoin Team homepage
