#ifndef KEVACOIN_CHAINPARAMSSEEDS_H
#define KEVACOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the kevacoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x64,0x15,0x74,0x77,0x24,0x7a,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x64,0x15,0x74,0x77,0x24,0x7a,
};
#endif // KEVACOIN_CHAINPARAMSSEEDS_H
